### ISSUE TITLE
globals.Headers is not a constructor (ky)

### ISSUE THREAD

**Issue by florian-lefebvre** [nuxt-community/strapi-module#126]
### Version
@nuxtjs/strapi: ^0.3.1
nuxt: ^2.15.3

I try to deploy a Nuxt SSR app to Vercel but I'm facing issues.
I'm using `nuxt-i18n` so I fetch data for each locale in the following `lang/strapi.js` file:
```js
export default async (context, locale) => {
  const fetched = await context.$strapi.graphql({
    query: `
    query {
      locales(where: { code: "${locale}" }) {
        some_field
      }
    }
    `
  });
  return await Promise.resolve(fetched.locales[0]);
};
```
It works when I fetch data from `http://localhost:1337` but fails with my prod setup at `https://example.com`.
When deployed on Vercel, my pages show "Nuxt Internal Server Error" and looking at functions in the dashboard, I have the following error:
```bash
[GET] /
16:40:36:23
2021-03-27T15:40:36.338Z	edfbbcbd-e114-4d55-9278-0c347a88be60	ERROR	[nuxt-i18n] Failed loading async locale export: globals.Headers is not a constructor
2021-03-27T15:40:36.338Z	edfbbcbd-e114-4d55-9278-0c347a88be60	DEBUG	Error occurred when calling nuxtServerInit:  globals.Headers is not a constructor
 ERROR  globals.Headers is not a constructor
  at mergeHeaders (node_modules_dev/ky/index.js:52:0)
  at deepMerge (node_modules_dev/ky/index.js:88:0)
  at validateAndMerge (node_modules_dev/ky/index.js:509:0)
  at Function.ky.<computed> [as post] (node_modules_dev/ky/index.js:516:0)
  at http_HTTP.module.exports.http_HTTP.<computed> [as post] (.nuxt/http.js:95:0)
  at http_HTTP.module.exports.http_HTTP.<computed> [as $post] (.nuxt/http.js:126:0)
  at strapi_Strapi.graphql (node_modules_dev/@nuxtjs/strapi/lib/runtime/strapi.js:122:0)
  at Store.update (store/api.js:17:0)
  at Array.wrappedActionHandler (node_modules_dev/vuex/dist/vuex.common.js:853:0)
  at Store.dispatch (node_modules_dev/vuex/dist/vuex.common.js:518:0)
```
I opened an issue https://github.com/nuxt-community/i18n-module/issues/1123 but it seems to be related with the `ky` module and so with the strapi module.
I found https://github.com/sindresorhus/ky-universal/issues/7 but I don't really know what to do now.

**Comment by florian-lefebvre** [comment]
Thanks, I think it's not the right place for this issue.
