### ISSUE TITLE
nuxt3: Cannot read property 'hooks' of undefined 

### ISSUE THREAD

**Issue by Zielgestalt** [nuxt-community/strapi-module#165]
### Version
@nuxtjs/strapi: v0.3.1
nuxt: v3.0.0-27235451.ece0e01

### Steps to reproduce
Fresh nuxt3 install. Added nuxt/strapi. Run 'yarn dev -o'

### What is Expected?
nuxt running

### What is actually happening?
Cannot start nuxt:  Cannot read property 'hooks' of undefined 15:36:55

  at Object.wrappedModule (node_modules/@nuxt/kit/dist/index.mjs:1092:13)
  at Object.installModule (node_modules/@nuxt/kit/dist/index.mjs:1196:17)
  at Object.strapiModule (node_modules/@nuxtjs/strapi/lib/module.js:39:14)
  at installModule (node_modules/@nuxt/kit/dist/index.mjs:1196:17)
  at initNuxt (node_modules/nuxt3/dist/index.mjs:817:11)
  at async load (node_modules/nuxi/dist/chunks/dev.mjs:6763:9)
  at async Object.invoke (node_modules/nuxi/dist/chunks/dev.mjs:6794:5)
  at async _main (node_modules/nuxi/dist/chunks/index.mjs:417:7)

✔ Generated nuxt.d.ts

**Comment by HenrijsS** [comment]
Any updates on this?

**Comment by Zielgestalt** [comment]
The new dev version works for me. See https://github.com/nuxt-community/strapi-module/blob/dev/docs/pages/2.setup.md#edge-channel

Thanks @benjamincanac for the great work!!!
