### ISSUE TITLE
Incompatible with nuxt generate and nuxt-bridge

### ISSUE THREAD

**Issue by tanc** [nuxt-community/strapi-module#171]
### Version
@nuxtjs/strapi: 0.3.1
nuxt: 3 with nuxt-bridge (I think!)

### Reproduction Link

https://codesandbox.io/s/nuxt-strapi-bridge-41h3g

### Steps to reproduce

Fire up the [codesandbox](https://codesandbox.io/s/nuxt-strapi-bridge-41h3g) and open a new terminal
Run `yarn generate`

### What is Expected?

A successful build with no errors

### What is actually happening?

The following error is thrown when running `nuxt generate`:

```
 FATAL  [worker] Directory import '/sandbox/node_modules/web-streams-polyfill/ponyfill/es2018' is not supported resolving ES modules imported from /sandbox/.nuxt/nitro/index.mjs
Did you mean to import web-streams-polyfill/dist/ponyfill.es2018.js?

  Did you mean to import web-streams-polyfill/dist/ponyfill.es2018.js?
  at finalizeResolution (internal/modules/esm/resolve.js:281:17)
  at moduleResolve (internal/modules/esm/resolve.js:708:10)
  at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:819:11)
  at Loader.resolve (internal/modules/esm/loader.js:89:40)
  at Loader.getModuleJob (internal/modules/esm/loader.js:242:28)
  at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:73:40)
  at link (internal/modules/esm/module_job.js:72:36)


   ╭──────────────────────────────────────────────────────────────────────────────────────────────────────╮
   │                                                                                                      │
   │   ✖ Nuxt Fatal Error                                                                                 │
   │                                                                                                      │
   │   Error: [worker] Directory import '/sandbox/node_modules/web-streams-polyfill/ponyfill/es2018' is   │
   │   not supported resolving ES modules imported from /sandbox/.nuxt/nitro/index.mjs                    │
   │   Did you mean to import web-streams-polyfill/dist/ponyfill.es2018.js?                               │
   │                                                                                                      │
   ╰──────────────────────────────────────────────────────────────────────────────────────────────────────╯

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by maninak** [comment]
It seems that that PR hasn't moved for a long time. We're starting up a fresh nuxt + strapi repo and would love to go with nuxt3 or at least nuxt2 + bridge or just nuxt2, but it's hard to make the call unless this is merged. @benjamincanac Is there a ballpark ETA of #168 getting merged? (thank you so much for working on this for all of us!)

**Comment by benjamincanac** [comment]
@maninak FYI The module is now ready for `nuxt3` and the new documentation is up: https://strapi.nuxtjs.org.

Let me know if you have any issue with it.
