### ISSUE TITLE
Module is not running after installation, "Cannot read properties of undefined (reading 'public')

### ISSUE THREAD

**Issue by Noxdor** [nuxt-community/strapi-module#266]
### Version
@nuxtjs/strapi: ^1.4.0
nuxt: latest (v3.0.0-rc.5)

### Steps to reproduce

Follow the guide on https://strapi.nuxtjs.org/setup. 

### What is Expected?

The project should load as expected. 

### What is actually happening?

I am getting an error message

```
 ERROR  Cannot restart nuxt:  Cannot read properties of undefined (reading 'public')

  at setup (node_modules/@nuxtjs/strapi/dist/module.mjs:25:32)
  at Object.normalizedModule (node_modules/@nuxtjs/strapi/node_modules/@nuxt/kit/dist/index.mjs:607:29)
  at async installModule (node_modules/@nuxt/kit/dist/index.mjs:340:3)
  at async initNuxt (node_modules/nuxt3/dist/index.mjs:1045:7)
  at async load (node_modules/nuxi/dist/chunks/dev.mjs:6724:9)
```

**Comment by Noxdor** [comment]
I found the issue, I created the project I was working on during the beta phase of Nuxt, so it was still using the `nuxt3` npm package and `nuxi` directly. That were the two differences I found by creating a fresh project to provide a reproduction link.
By changing `nuxt3` to `nuxt`, providing the latest version number for that and also changing `nuxi` to `nuxt` in the npm scripts, the issues were resolved (I had to also remove the `node_modules` folder and `package-lock.json` and freshly install).
I am not sure why this happened, but I think it is because the beta didn't support modules, since `defineNuxtConfig` also threw typescript errors once I added the `strapi` key. Now it doesn't, which makes me think adding modules was not possible in the beta.
Hope this helps someone migrating from the beta running into the same issue with nuxt modules.
