### ISSUE TITLE
$users.update('me', form) not working

### ISSUE THREAD

**Issue by merijnponzo** [nuxt-community/strapi-module#80]
Hello,

with strapi 3.1.4
and a postgress database

I'm not able to update users/me

I added users as a entity within nuxt config
```
 strapi: {
    entities: ['users'],
  },
```
then i want to change a single field called 'accounttype'

```
const form = {accounttype:2}
const user = await this.$strapi.$users.update('me', form)
```

Then i got this error:

```
] error error: invalid input syntax for type integer: "me"
    at Parser.parseErrorMessage (/Applications/projects/testapp/backend/node_modules/pg-protocol/dist/parser.js:278:15)
    at Parser.handlePacket (/Applications/projects/testapp/backend/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/Applications/projects/testapp/backend/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/Applications/projects/testapp/backend/node_modules/pg-protocol/dist/index.js:8:42)
    at Socket.emit (events.js:315:20)
    at Socket.EventEmitter.emit (domain.js:483:12)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:271:9)
    at Socket.Readable.push (_stream_readable.js:212:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:186:23)
From previous event:
    at Client_PG._query (/Applications/projects/testapp/backend/node_modules/knex/lib/dialects/postgres/index.js:234:12)
    at Client_PG.query (/Applications/projects/testapp/backend/node_modules/knex/lib/client.js:158:17)
    at Runner.query (/Applications/projects/testapp/backend/node_modules/knex/lib/runner.js:135:36)
    at /Applications/projects/testapp/backend/node_modules/knex/lib/runner.js:39:23
From previous event:
    at Runner.run (/Applications/projects/testapp/backend/node_modules/knex/lib/runner.js:25:16)
    at Builder.Target.then (/Applications/projects/testapp/backend/node_modules/knex/lib/interface.js:14:43)
    at processImmediate (internal/timers.js:456:21)
[2020-11-19T12:54:53.055Z] debug PUT /users/me (61 ms) 500
```

**Comment by merijnponzo** [comment]
I guess, like the error says the endpoint is expecting an integer- a user id instead of 'me'

```
const user = await this.$strapi.$users.update(5, { accounttype: 2 })
```

So within the documentation:
```
Updating current user
You often need to update your user, and so on define a custom route in Strapi: PUT /users/me.
```

I found some topics about the endpoint users/me, updating users- with or without custom endpoints and policies.
In my opinion it's a bit confusing

**Comment by unremarkablegarden** [comment]
How do I set up users/me?

**Comment by benjamincanac** [comment]
@unremarkablegarden You have to implement the route on your API as it not there by default in Strapi.

You can do so by overriding `/extensions/users-permissions/controllers/User.js` and adding a function like this:

```
async updateme (ctx) {
  const { id } = ctx.state.user

  const user = await strapi.plugins['users-permissions'].services.user.edit({ id }, omit(ctx.request.body, ['id', 'email', 'username', 'password']))
  return sanitizeUser(user)
}
```

and its associated route defined in `/extensions/users-permissions/config/routes.json`:

```
{
  "method": "PUT",
  "path": "/users/me",
  "handler": "User.updateme",
  "config": {
    "policies": [
      "plugins::users-permissions.isAuthenticated"
    ]
  }
}
```
